### ISSUE TITLE
Circular import raises ImportError

### ISSUE THREAD

**Issue by Z33DD** [amiralis/geo-mapper#1]
```
❯ python script.py
Traceback (most recent call last):
  File "/home/z33dd/Codes/Python/script.py", line 3, in <module>
    from geomap import Map
  File "/home/z33dd/.local/lib/python3.9/site-packages/geomap/__init__.py", line 1, in <module>
    from geomap import Map
ImportError: cannot import name 'Map' from partially initialized module 'geomap' (most likely due to a circular import) (/home/z33dd/.local/lib/python3.9/site-packages/geomap/__init__.py)
```
And "import geomap" raises the same error

**Comment by SerhatYildrm** [comment]
> ```
> ❯ python script.py
> Traceback (most recent call last):
>   File "/home/z33dd/Codes/Python/script.py", line 3, in <module>
>     from geomap import Map
>   File "/home/z33dd/.local/lib/python3.9/site-packages/geomap/__init__.py", line 1, in <module>
>     from geomap import Map
> ImportError: cannot import name 'Map' from partially initialized module 'geomap' (most likely due to a circular import) (/home/z33dd/.local/lib/python3.9/site-packages/geomap/__init__.py)
> ```
> 
> And "import geomap" raises the same error

Change "from geomap import Map" to "from .geomap import Map"  in __init__.py.
